---
# TODO: When MrP has user control, add users here.

- hosts: localhost
  gather_facts: no
  vars:
         mr_provisioner_do_provision: False
         mr_provisioner_url: "http://10.40.0.11:5000"
  vars_files:
          - vars/mrp_creds.yml.secret
          - vars/list_preseeds.yml
  roles:
          - role: ansible-role-mr-provisioner
  tasks:
          - name: Upload preseed from info in list_preseed.yml
            mr_provisioner_preseed:
                    name: "{{ item.name }}"
                    description: "{{ item.description }}"
                    type: "{{ item.type }}"
                    path: "{{ item.path }}"
                    url: "{{ mr_provisioner_url }}"
                    token: "{{ mr_provisioner_auth_token }}"
                    public: "{{ item.public | default(true) }}"
                    known_good: "{{ item.known_good | default(true) }}"
            with_items: "{{ list_preseeds }}"

# TODO: When MrP allows adding users to machines, add jenkins user to all

- hosts: jenkins
  gather_facts: yes
  remote_user: root
  tasks:
          - include_vars:
                file: ./vars/jslave_tokens.yml.secret

          - name: Clear token files first
            file:
                state: absent
                path: "/home/{{ item.jslave }}/mrp_token"
            with_items: "{{ jslave_tokens }}"

          - name: Put the tokens
            lineinfile:
                path: "/home/{{ item.jslave }}/mrp_token"
                create: yes
                line: "{{ item.token }}"
            with_items: "{{ jslave_tokens }}"
