---
- hosts: target
  tasks:
        - include_tasks: ./tasks/install_packages.yml
          vars:
            packages_to_install:
              - python3
              - python3-pip
              - git
              - build-essential
              - linux-perf
              - unzip
              - lhasa

        - name: Wipe harness directory
          file:
              path: "benchmark_harness"
              state: "{{ item }}"
          with_items:
              - absent
              - directory

        - name: Get the benchmark_harness
          git:
              repo: https://github.com/Linaro/benchmark_harness.git
              dest: benchmark_harness
              version: "{{ branch | default('master') }}"

        - name: Install pip requirements
          shell: python3 -m pip install -r ./benchmark_harness/requirements.txt

        - name: Wipe results directory
          file:
              path: "results"
              state: "{{ item }}"
          with_items:
              - absent
              - directory

        - include_tasks: ./tasks/call_harness.yml

        - name: Find where the harness put the results
          find:
            paths: "results"
            patterns: '{{ benchmark }}*'
            file_type: directory
          register: benchresults_path
        - debug: var=benchresults_path.files

        - name: Find results
          find:
            paths: "{{ item.path }}/results/"
            patterns: "^.*?\\.(?:err|out)$"
            use_regex: yes
          with_items: "{{ benchresults_path.files }}"
          register: reports_path
          failed_when: reports_path.matched == 0
        - debug: var=reports_path

        - name: Make a directory with a nice name for sftp
          file:
            path: "results/{{ sftp_dirname }}"
            state: directory

        - name: Copy results
          copy:
            src: "{{ item.path }}"
            dest: "results/{{ sftp_dirname}}/{{ item.path | basename }}"
            remote_src: yes
          with_items: "{{ reports_path.results[0].files }}"

        - include_tasks: ./tasks/put_sftp.yml
          vars:
            dirs_to_sftp: "results/{{ sftp_dirname }}"

        - name: Remove the old dir
          file: 
            state: absent
            path: "{{ item.path }}/"
          with_items: "{{ benchresults_path.files }}"

        - name: Remove the nicely named sftp dir
          file:
            state: absent
            path: "results/{{ sftp_dirname }}/"
