---
- name: Create the Jenkins slaves
  user:
          name: "{{ item }}"
          shell: "/bin/bash"
          generate_ssh_key: no
          group: "jenkins_slave"
  with_list: "{{ jslave_list }}"

- name: Create the slaves .ssh directory
  file:
          name: "/home/{{ item }}/.ssh"
          state: directory
          owner: "{{ item }}"
          mode: 0700
  with_list: "{{ jslave_list }}"

- name: Copy the ssh_keys from the remote
  copy:
      src: "{{ key_path }}"
      dest: "/home/{{ item }}/.ssh/id_rsa"
      remote_src: yes
  with_list: "{{ jslave_list }}"

- name: Fetch the ssh_keys from the remote
  fetch:
      src: "{{ key_path }}.pub"
      dest: "./templates/{{ item }}.sshkey"
      flat: yes
  with_list: "{{ jslave_list }}"

- name: Putting the keys into the template for the fileserver
  template:
    src: "templates/jslaves-openhpc.yml.j2"
    dest: "/tmp/jslaves-openhpc.yml"

- name: Putting the keys into the template for the fileserver
  template:
    src: "templates/jslaves-benchmark.yml.j2"
    dest: "/tmp/jslaves-benchmark.yml"
    
- name: Get the template back
  fetch:
    src: "/tmp/{{ item }}"
    dest: "./vars/{{ item }}.secret"
    flat: yes
  with_items:
        - jslaves-benchmark.yml
        - jslaves-openhpc.yml

- name: Add Master Jenkins' ssh key to the slaves authorized list
  authorized_key:
          user: "{{ item }}"
          state: present
          key: "{{ master_sshkey }}" 
  with_list: "{{ jslave_list }}"

- name: Copy the playbook maker script to their home dir
  copy:
          src: "../files/provisioning.py"
          dest: "/home/{{ item }}/"
          owner: "{{ item }}"
          group: "jenkins_slave"
          mode: u=rx,g=rx,o=rwx 
  with_list: "{{ jslave_list }}"
