---

- name: Create the Jenkins slaves
  user:
          name: "{{ item }}"
          shell: "/bin/bash"
          generate_ssh_key: yes
          group: "jenkins_slave"
  with_list: "{{ jslave_list }}"

- name: Fetch the ssh_keys from the remote
  fetch:
      src: "/home/{{ item }}/.ssh/id_rsa.pub"
      dest: "./{{ item }}.sshkey"
      flat: yes
  with_list: "{{ jslave_list }}"

- name: Putting the keys into the template for the fileserver
  template:
    src: templates/jslaves.yml.j2
    dest: /tmp/jslaves.yml

- name: Get the template back
  fetch:
    src: /tmp/jslaves.yml
    dest: ./
    flat: yes

- name: Add Master Jenkins' ssh key to the slaves authorized list
  authorized_key:
          user: "{{ item }}"
          state: present
          key: "{{ master_sshkey }}" 
  with_list: "{{ jslave_list }}"

- name: Add their own key to their authorized list
  authorized_key:
          user: "{{ item }}"
          state: present
          key: "{{ lookup('file', './{{ item }}.sshkey') }}"
  with_list: "{{ jslave_list }}"

- name: Copy the playbook maker script to their home dir
  copy:
          src: "../files/provisioning.py"
          dest: "/home/{{ item }}/"
          owner: "{{ item }}"
          group: "jenkins_slave"
          mode: u=rx,g=rx,o=rwx 
  with_list: "{{ jslave_list }}"
