---
python3: "/usr/bin/python3"
user: "builder"
build_id: "42"
dir_root: "/home/{{ user }}/{{ build_id }}"
dir_home: "{{ dir_root }}/tensorflow_build"
dir_repo: "{{ dir_root }}/repo_tensorflow"
dir_built: "{{ dir_root }}/built_tarballs"
venv_path: "{{ dir_root }}/virtualenv"

#dir_src: "{{ dir_home }}/{{ package.name }}/{{ package_version}}"

# NumPy variables
numpy:
       name: "numpy"
       version: "1.17.3"
       release_url: "https://github.com/numpy/numpy/releases/download/v1.17.2/numpy-1.17.3.zip"
       release_zip: "numpy-1.17.3.zip"
       release_sha256: "a0678793096205a4d784bd99f32803ba8100f639cf3b932dc63b21621390ea7e"
       dir_base: "{{ dir_home }}/{{ name }}"
       dir_src: "{{ dir_base }}/{{ version }}"
       dir_output: "{{ dir_src }}/dist"
       wheel: "{{ dir_output }}/numpy-1.17.3-py3.6-linux-aarch64.egg"
       patching_required: true
       patch: 'numpy_centos7_aarch64.patch'
       built_tarball: "numpy_{{ version }}_{{ build_id }}"

# TensorFlow variables
tensorflow:
       name: "tensorflow"
       version: "1.15.0-rc2"
       release_url: "https://github.com/tensorflow/tensorflow/archive/v1.15.0.zip"
       release_zip: "v1.15.0.zip"
       dir_base: "{{ dir_home }}/{{ name }}"
       dir_src: "{{ dir_base }}/{{ version }}"
       dir_output: "/tmp/tensorflow_pkg"
       wheel: "{{ dir_output }}/tensorflow-1.15.0-cp36-cp36m-linux_aarch64.whl"
       patching_required: true
       patch: 'patch_bazelbuild.patch'
       built_tarball: "tensorflow_{{ version }}_{{ build_id }}"
       cxx_optimizations:
               - "-D_GLIBCXX_USE_CXX11_ABI=0"
       c_optimizations:
               - "-funsafe-math-optimizations"
               - "-ftree-vectorize"
               - "-fomit-frame-pointer"

# Bazel variables
bazel:
       name: "bazel"
       version: "0.24.1"
       release_url: "https://github.com/bazelbuild/bazel/releases/download/0.24.1/bazel-0.24.1-dist.zip"
       release_zip: "bazel-0.24.1-dist.zip"
       dir_base: "{{ dir_home }}/{{ name }}"
       dir_src: "{{ dir_base }}/{{ version }}"
       dir_output: "{{ dir_src }}/output"
       binary: "{{ dir_output }}/bazel"
       patching_required: false
       built_tarball: "bazel_{{ version }}_{{ build_id }}"


ohpc_toolchain_lib_dir: "/opt/ohpc/pub/compiler/gcc/8.3.0/lib64"

### BUILD DEPENDENCIES
# Non OHPC, non python, non java
tf_build_dependencies:
        - "@Development Tools"
        - createrepo
        - vim
        - wget
        - unzip
        - tar
        - redhat-lsb-core

ohpc_release_url: "http://build.openhpc.community/OpenHPC:/1.3/CentOS_7/aarch64/ohpc-release-1.3-1.el7.aarch64.rpm"

tf_build_ohpc_dependencies:
        - lmod-ohpc
        - openmpi3-gnu8-ohpc
        - ohpc-gnu8-perf-tools
        - ohpc-gnu8-io-libs
        - ohpc-gnu8-python-libs
        - ohpc-gnu8-runtimes
        - ohpc-gnu8-serial
        - ohpc-gnu8-parallel-libs
        - lmod-defaults-gnu8-openmpi3-ohpc

tf_build_java8:
        - java-1.8.0-openjdk
        - java-1.8.0-openjdk-devel

tf_build_py3_dependencies:
        - pip
        - six
        - wheel
        - setuptools
        - mock
        - "future>=0.17.1"

tf_build_keras:
        - "keras_applications==1.0.6"
        - "keras_preprocessing==1.0.5"

# SciPy ? openBLAS ?
