---

python3: "/usr/bin/python3"
user: "builder"
dir_root: "/home/{{ user }}"
dir_home: "{{ dir_root }}/tensorflow_build"
dir_repo: "{{ dir_root }}/repo_tensorflow"

#dir_src: "{{ dir_home }}/{{ package.name }}/{{ package_version}}"

# NumPy variables
numpy:
       name: "numpy"
       version: "1.17.2"
       release_url: "https://github.com/numpy/numpy/releases/download/v1.17.2/numpy-1.17.2.zip"
       release_zip: "numpy-1.17.2.zip"
       dir_base: "{{ dir_home }}/{{ name }}"
       dir_src: "{{ dir_base }}/{{ version }}"
       dir_output: "{{ dir_src }}/dist"
       wheel: "{{ dir_output }}/numpy-1.17.2-py3.6-linux-aarch64.egg"
       patching_required: true
       patch: 'numpy_centos7_aarch64.patch'

# TensorFlow variables
tensorflow:
       name: "tensorflow"
       version: "1.15.0-rc2"
       release_url: "https://github.com/tensorflow/tensorflow/archive/v1.15.0-rc2.zip"
       release_zip: "v1.15.0-rc2.zip"
       dir_base: "{{ dir_home }}/{{ name }}"
       dir_src: "{{ dir_base }}/{{ version }}"
       dir_output: "/tmp/tensorflow_pkg"
       wheel: "{{ dir_output }}/tensorflow-1.15.0rc2-cp36-cp36m-linux_aarch64.whl"
       patching_required: true
       patch: 'patch_bazelbuild.patch'

# Bazel variables
bazel:
       name: "bazel"
       version: "0.24.1"
       release_url: "https://github.com/bazelbuild/bazel/releases/download/0.24.1/bazel-0.24.1-dist.zip"
       release_zip: "bazel-0.24.1-dist.zip"
       dir_base: "{{ dir_home }}/{{ name }}"
       dir_src: "{{ dir_base }}/{{ version }}"
       dir_output: "{{ dir_src }}/output"
       binary: "{{ dir_output }}/bazel"
       patching_required: false

# SciPy ? openBLAS ?
