---
- name: Get the bazel_repo file for yum
  template:
          src: bazel.repo.j2
          dest: /etc/yum.repo.d/bazel.repo

- name: Install bazel from the repo
  yum:
          name: bazel-{{ bazel_version }}-{{ bazel_minorversion }}
          state: present
