---
- name: Install apt dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - python3
    - python3-pip
    - git
    - build-essential
    - linux-perf
    - unzip
    - lhasa
