---
- name: Install apt dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - python3
    - python3-pip
    - git
    - build-essential
    - linux-perf
    - linux-reference-perf
    - unzip
    - lhasa

- name: Set perf CAP_SYS_ADMIN level to 2
  shell: echo '2' | tee  /proc/sys/kernel/perf_event_paranoid  
