---
- name: Remove the old dir
  file: 
    state: absent
    path: "{{ item.path }}/"
  with_items: "{{ benchresults_path.files }}"

- name: Remove the nicely named sftp dir
  file:
    state: absent
    path: "results/{{ sftp_dirname }}/"
