---
- include_tasks: ./tasks/install_packages.yml
  vars:
    packages_to_install:
      - python3
      - python3-pip
      - git
      - build-essential
      - linux-perf
      - unzip
      - lhasa

- name: Wipe harness directory
  file:
      path: "benchmark_harness"
      state: "{{ item }}"
  with_items:
      - absent
      - directory

- name: Get the benchmark_harness
  git:
      repo: https://github.com/Linaro/benchmark_harness.git
      dest: benchmark_harness
      version: "{{ branch | default('master') }}"

- name: Install pip requirements
  shell: python3 -m pip install -r ./benchmark_harness/requirements.txt

- name: Wipe results directory
  file:
      path: "results"
      state: "{{ item }}"
  with_items:
      - absent
      - directory
