---
- name: Copy results to fileserver
  shell: (echo "mkdir {{ sftp_dirname }}" && echo "cd {{ sftp_dirname }}" && echo "put {{ item.path }}" && echo "exit") | sftp -o ForwardAgent=yes -o ConnectTimeout=60 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no  {{sftp_user}}@{{ sftp_server_ip }}:/{{ sftp_path }}
  with_items:
    - "{{ files_to_sftp }}"
